# Generated by Django 3.1 on 2022-06-29 06:56

from django.db import migrations, models
import garpix_menu.models.menu_item


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_menu', '0004_auto_20220111_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='sites',
            field=models.ManyToManyField(default=garpix_menu.models.menu_item.get_all_sites, to='sites.Site', verbose_name='Сайты для отображения'),
        ),
    ]
