# Generated by Django 3.2 on 2023-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0006_menuitem_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
