# Generated by Django 3.2 on 2023-02-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0007_menuitem_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='subpage_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='URL подстраницы (при наличии)'),
        ),
    ]
