# Generated by Django 4.2 on 2024-10-14 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0010_menuitem_css_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('sort',), 'verbose_name': 'Пункт меню | Menu Point', 'verbose_name_plural': 'Пункты меню | Menu Points'},
        ),
    ]
