# Generated by Django 3.2 on 2023-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Содержание'),
        ),
    ]
